import pages, {
  MapView,
  Settings
} from './pages';

export const PAGE_PATHS = [
  {
    index: true,
    component: MapView
  },
  {
    path: 'settings',
    component: Settings
  }
];

export const REDUX_ACTIONS = {
  SATELLITE_SET_BEARING: 'SATELLITE_SET_BEARING',
  SATELLITE_SET_LON_LAT: 'SATELLITE_SET_LON_LAT',
  SATELLITE_SET_TLE: 'SATELLITE_SET_TLE',
  SATELLITES_SET: 'SATELLITES_SET',
  SATELLITE_SET_LOOK_ANGLES: 'SATELLITE_SET_LOOK_ANGLES',
  USER_SET_LON_LAT: 'USER_SET_LON_LAT',
  USER_DENIED_GEOLOCATION: 'USER_DENIED_GEOLOCATION',
  USER_SET_TIME: 'USER_SET_TIME',
  USER_SET_TIME_MS: 'USER_SET_TIME_MS',
  MAP_DESTROY: 'MAP_DESTROY',
  MAP_INIT: 'MAP_INIT',
  MAP_TOGGLE_3D_VIEW: 'MAP_TOGGLE_3D_VIEW',
  MAP_TOGGLE_SATELLITE_VIEW: 'MAP_TOGGLE_SATELLITE_VIEW',
  MAP_SET_BEARING: 'MAP_SET_BEARING',
  MAP_SET_STYLE: 'MAP_SET_STYLE'
};

export const MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiZnJhbmtzdmFsbGkiLCJhIjoiSFd2NDgxdyJ9.86RUhUDNQtjWdZysxDIzuw';

export default {
  PAGE_PATHS,
  REDUX_ACTIONS,
  MAPBOX_ACCESS_TOKEN
}