name: TLE update
on:
  push:
  schedule:
    - cron: "7 12 * * *" # runs daily at 12:07pm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Fetch new TLEs
        run: npm run tle-update
        shell: bash
      - name: Check in TLE updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Daily TLE update (bot)"
          git push
